// Référentiel d'audit EPLE — domaines + contrôles (fiches métier).
// Source unique : tous les écrans consomment ce référentiel (aucun doublon).
// Inspiré CIC DGFiP/DRFiP, M9-6, guides académiques. Les budgets annexes
// (GRETA/CFA) ajoutent le contrôle des salaires et des vacations.

import type { DomaineDef, ControleDef } from "./types";

export const DOMAINES: DomaineDef[] = [
  { id: "gouvernance", libelle: "Gouvernance" },
  { id: "comptabilite", libelle: "Comptabilité générale" },
  { id: "depenses", libelle: "Dépenses" },
  { id: "recettes", libelle: "Recettes" },
  { id: "recouvrement", libelle: "Recouvrement / contentieux" },
  { id: "tresorerie", libelle: "Trésorerie" },
  { id: "regies", libelle: "Régies" },
  { id: "valeurs_inactives", libelle: "Valeurs inactives" },
  { id: "fdr", libelle: "Fonds de roulement" },
  { id: "immobilisations", libelle: "Immobilisations" },
  { id: "stocks", libelle: "Stocks" },
  { id: "commande_publique", libelle: "Commande publique" },
  { id: "rh", libelle: "Ressources humaines" },
  { id: "logements", libelle: "Logements de fonction" },
  { id: "fonds_sociaux", libelle: "Fonds sociaux / bourses" },
  { id: "greta", libelle: "GRETA", budgets: ["GRETA"] },
  { id: "cfa", libelle: "CFA / Apprentissage", budgets: ["CFA"] },
  { id: "compte_financier", libelle: "Compte financier" },
];

// Fabrique compacte d'une fiche de contrôle.
const c = (
  id: string, domaineId: string, sousDomaine: string, intitule: string,
  objectif: string, risque: ControleDef["risque"], fondement: string[],
  documentsAttendus: string[], methode: string,
  extra: Partial<ControleDef> = {},
): ControleDef => ({ id, domaineId, sousDomaine, intitule, objectif, risque, fondement, documentsAttendus, methode, ...extra });

export const CONTROLES: ControleDef[] = [
  // ───────── Gouvernance ─────────
  c("gouv-deleg", "gouvernance", "Délégations", "Délégations de signature à jour",
    "Vérifier l'existence et la validité des délégations (ordonnateur, agent comptable).", "important",
    ["Code éduc. R421-13", "GBCP"], ["Actes de délégation", "Publication"],
    "Contrôler la chaîne de délégations, leur publication et leur cohérence avec les habilitations Op@le."),
  c("gouv-sepa", "gouvernance", "Séparation des fonctions", "Séparation ordonnateur / comptable",
    "S'assurer de la stricte séparation des sphères ordonnateur et comptable.", "critique",
    ["GBCP art. 9", "M9-6"], ["Organigramme fonctionnel", "Habilitations Op@le"],
    "Vérifier qu'aucun agent ne cumule des fonctions incompatibles (engagement/paiement)."),
  c("gouv-cic", "gouvernance", "Contrôle interne", "Dispositif de contrôle interne comptable",
    "Vérifier l'existence d'un plan de contrôle interne et son application.", "important",
    ["M9-6 tome 4 §215", "RGP 2022-408"], ["Plan de contrôle", "PV de contrôle"],
    "Examiner la cartographie des risques et la traçabilité des contrôles réalisés."),

  // ───────── Comptabilité générale ─────────
  c("compta-attente", "comptabilite", "Comptes d'attente", "Apurement des comptes d'attente (47)",
    "Vérifier l'absence d'opérations anciennes non régularisées en comptes d'attente.", "important",
    ["M9-6", "GBCP"], ["Balance", "Grand livre comptes 47"],
    "Lister les soldes 47x anciens ; vérifier leur apurement régulier.",
    { alerteAuto: "Soldes de comptes d'attente (47) anciens non régularisés." }),
  c("compta-tiers", "comptabilite", "Comptes de tiers", "Apurement / provisionnement des comptes de tiers",
    "Détecter les comptes de tiers (41/40) anciens non apurés ou non provisionnés (491).", "important",
    ["M9-6", "GBCP"], ["Balance âgée", "Comptes 41/40/491"],
    "Analyser l'ancienneté des créances/dettes ; vérifier les dépréciations (491).",
    { alerteAuto: "Comptes de tiers anciens non apurés / non provisionnés (491)." }),
  c("compta-etat-coll", "comptabilite", "Imputation des financements", "Distinction État / Collectivité",
    "Vérifier la juste imputation des financements État (4411/7411) vs Collectivité (4412/74121).", "moyen",
    ["M9-6", "Op@le — activités 1 État / 2 Collectivité"], ["Notifications", "Balance"],
    "Rapprocher les notifications et l'imputation par activité Op@le.",
    { alerteAuto: "Confusion comptes État (4411/7411) / Collectivité (4412/74121)." }),
  c("compta-rappro", "comptabilite", "Rapprochements", "Cohérence balance / journaux / comptes",
    "Vérifier la cohérence interne des états comptables.", "moyen",
    ["M9-6"], ["Balance", "Journaux", "Compte de gestion"],
    "Rapprocher balance, grand livre et journaux ; détecter les écarts."),

  // ───────── Dépenses ─────────
  c("dep-pj", "depenses", "Pièces justificatives", "Complétude et conformité des PJ",
    "Vérifier la présence et la conformité des pièces justificatives de la dépense.", "important",
    ["GBCP art. 19/20", "Décret PJ", "CCP"], ["Demandes de paiement", "Factures", "Bons"],
    "Échantillonner des demandes de paiement ; contrôler les PJ exigibles (Op@le)."),
  c("dep-sf", "depenses", "Service fait", "Certification du service fait",
    "S'assurer de la certification du service fait avant paiement.", "critique",
    ["GBCP art. 31", "M9-6"], ["Attestation de service fait"],
    "Vérifier l'antériorité et la certification du service fait par l'ordonnateur."),
  c("dep-delai", "depenses", "Délai global de paiement", "Respect du DGP (30 jours)",
    "Mesurer le respect du délai global de paiement et les intérêts moratoires.", "moyen",
    ["Décret 2013-269", "CCP"], ["Journal des demandes de paiement"],
    "Calculer le délai réception → paiement ; détecter les dépassements.",
    { alerteAuto: "Dépassements récurrents du délai global de paiement." }),
  c("dep-chq", "depenses", "Moyens de paiement", "Paiement par virement (et non chèque)",
    "Vérifier que les fournisseurs sont payés par virement.", "moyen",
    ["M9-6", "Instruction trésorerie"], ["États de paiement"],
    "Détecter les paiements fournisseurs par chèque.",
    { alerteAuto: "Fournisseurs payés par chèque au lieu de virement." }),

  // ───────── Recettes ─────────
  c("rec-or", "recettes", "Ordres de recettes", "Émission régulière des ordres de recettes",
    "Vérifier l'émission et le suivi des ordres de recettes.", "moyen",
    ["GBCP", "M9-6"], ["Ordres de recettes", "Titres"],
    "Contrôler la chaîne constatation → liquidation → émission."),
  c("rec-rar", "recettes", "Restes à recouvrer", "Suivi des restes à recouvrer et prescription",
    "Détecter les créances proches de la prescription non poursuivies (SATD à émettre).", "critique",
    ["CGPPP", "M9-6", "Code éduc."], ["Balance âgée des créances", "Relances", "SATD"],
    "Analyser l'ancienneté des RAR ; vérifier les diligences de recouvrement.",
    { alerteAuto: "Créances proches de la prescription non poursuivies (SATD à émettre)." }),
  c("rec-anv", "recettes", "Admissions en non-valeur", "ANV et remises gracieuses régulières",
    "Vérifier la régularité des ANV et remises gracieuses (délibération CA).", "moyen",
    ["M9-6", "Code éduc. R421-20"], ["Délibérations CA", "États ANV"],
    "Contrôler la délibération préalable et la justification des ANV."),
  c("rec-bourses", "recettes", "Bourses", "Circuit comptable des bourses",
    "Vérifier le circuit 44311 → 468 → 411 des bourses nationales.", "important",
    ["M9-6", "Code éduc."], ["Notifications bourses", "Balance comptes 44311/468/411"],
    "Rapprocher notifications et écritures ; détecter les incohérences de circuit.",
    { alerteAuto: "Bourses : circuit 44311 → 468 → 411 incohérent." }),

  // ───────── Trésorerie ─────────
  c("treso-rappro", "tresorerie", "Rapprochements bancaires", "Rapprochement bancaire mensuel",
    "Vérifier la réalisation et la justification des rapprochements bancaires.", "important",
    ["M9-6", "GBCP"], ["États de rapprochement", "Relevés DFT"],
    "Contrôler la périodicité et l'apurement des suspens.",
    { alerteAuto: "Rapprochement bancaire non réalisé / suspens anciens." }),
  c("treso-quotidien", "tresorerie", "Contrôle quotidien", "Contrôle quotidien de trésorerie",
    "S'assurer du suivi quotidien des disponibilités (compte DFT).", "moyen",
    ["M9-6"], ["Journal de trésorerie"],
    "Vérifier la tenue du contrôle quotidien et la position du compte au Trésor."),

  // ───────── Régies ─────────
  c("reg-arrete", "regies", "Création / arrêtés", "Arrêtés de régie et nominations à jour",
    "Vérifier l'existence des arrêtés constitutifs et des actes de nomination.", "important",
    ["Décret 2019-798", "Décret 2020-542", "M9-6"], ["Arrêtés de régie", "Actes de nomination"],
    "Contrôler la conformité des arrêtés et leur mise à jour."),
  c("reg-caution", "regies", "Cautionnement", "Cautionnement du régisseur",
    "Vérifier la constitution du cautionnement selon le montant de l'encaisse.", "moyen",
    ["Arrêté cautionnement", "M9-6"], ["Justificatif de cautionnement"],
    "Rapprocher l'encaisse maximale autorisée et le cautionnement."),
  c("reg-verif", "regies", "Vérifications", "PV de vérification de régie + encaisse",
    "Vérifier les contrôles (dont inopinés) et le respect de l'encaisse maximale.", "critique",
    ["M9-6", "Décret 2019-798"], ["PV de vérification", "Comptes de régie"],
    "Contrôler la périodicité des vérifications et le plafond d'encaisse.",
    { alerteAuto: "Régie sans PV de vérification ou encaisse > maximum autorisé." }),

  // ───────── Fonds de roulement ─────────
  c("fdr-calcul", "fdr", "Calcul / couverture", "Niveau de fonds de roulement (jours)",
    "Apprécier le FdR en jours de fonctionnement et sa soutenabilité.", "moyen",
    ["M9-6 tome 1 §V"], ["Bilan", "Balance"],
    "Calculer FdR / charges décaissables × 365 ; comparer aux seuils prudentiels."),
  c("fdr-prelev", "fdr", "Prélèvements", "Régularité des prélèvements sur FdR",
    "Vérifier que les prélèvements sont justifiés et délibérés.", "moyen",
    ["M9-6", "Code éduc. R421-20"], ["Délibérations CA"],
    "Contrôler la délibération et l'affectation des prélèvements."),

  // ───────── Immobilisations ─────────
  c("immo-inv", "immobilisations", "Inventaire", "Concordance inventaire / comptabilité (21x/28x)",
    "Vérifier la concordance entre l'inventaire physique et les comptes.", "important",
    ["M9-6", "RGP 2022-408"], ["Inventaire", "Balance comptes 21/28"],
    "Rapprocher inventaire et soldes ; contrôler les amortissements.",
    { alerteAuto: "Écarts inventaire / comptabilité des immobilisations (21x/28x)." }),
  c("immo-sorties", "immobilisations", "Sorties", "Sorties d'inventaire / réformes justifiées",
    "Vérifier la régularité des sorties et réformes de biens.", "moyen",
    ["M9-6", "Code éduc."], ["PV de réforme", "Délibérations"],
    "Contrôler l'autorisation et la traçabilité des sorties."),

  // ───────── Stocks ─────────
  c("stock-inv", "stocks", "Inventaire / valorisation", "Inventaire physique et valorisation (CMUP/FIFO)",
    "Vérifier l'inventaire de fin d'exercice et la méthode de valorisation.", "moyen",
    ["M9-6 — comptabilité matières", "RGP 2022-408"], ["Inventaire stocks", "Comptes 31/32/37"],
    "Rapprocher inventaire et comptes ; contrôler la constance de la méthode."),

  // ───────── Commande publique ─────────
  c("cp-seuils", "commande_publique", "Seuils / procédures", "Respect des seuils et procédures",
    "Vérifier la procédure au regard des seuils (saucissonnage).", "critique",
    ["CCP", "Code de la commande publique"], ["Marchés", "Devis", "Publicité"],
    "Analyser les achats par fournisseur/objet ; détecter le fractionnement.",
    { alerteAuto: "Dépassement de seuil CCP sans procédure (saucissonnage)." }),
  c("cp-publicite", "commande_publique", "Publicité / concurrence", "Publicité et mise en concurrence",
    "Vérifier la publicité et la mise en concurrence effectives.", "important",
    ["CCP"], ["Avis de publicité", "Offres", "Rapport de présentation"],
    "Contrôler la traçabilité de la mise en concurrence."),

  // ───────── Ressources humaines (dont salaires/vacations) ─────────
  c("rh-contrats", "rh", "Contrats", "Régularité des contrats et actes RH",
    "Vérifier l'existence et la régularité des contrats des agents.", "moyen",
    ["Décret 86-83", "Code éduc."], ["Contrats", "Arrêtés"],
    "Contrôler la base juridique, la quotité et l'indice."),
  c("rh-salaires", "rh", "Rémunérations / salaires", "Concordance paie / contrats / indices",
    "Contrôler les rémunérations payées au regard des contrats, indices et quotités.", "important",
    ["M9-6", "Décret 86-83", "Op@le paie"], ["Bulletins de paie", "Export OPER@", "Contrats"],
    "Rapprocher les éléments de paie (brut, indice, charges) avec les actes ; détecter les anomalies de taux/net.",
    { alerteAuto: "Rémunération payée incohérente avec le contrat / l'indice." }),
  c("rh-vacations", "rh", "Vacations", "Contrôle des vacations (heures, taux, service fait)",
    "Vérifier les vacations : heures effectuées, taux appliqué, service fait, plafonds.", "important",
    ["M9-6", "Décret 86-83", "Barèmes vacations"], ["États de vacations", "Ordres de mission", "Service fait"],
    "Rapprocher heures déclarées et service fait ; contrôler le taux horaire et les plafonds.",
    { alerteAuto: "Vacations payées sans service fait justifié ou taux non conforme." }),
  c("rh-iffca", "rh", "IFFCA / indemnités", "Régularité des IFFCA et indemnités",
    "Vérifier la base et le calcul des IFFCA / indemnités.", "moyen",
    ["Textes indemnitaires", "M9-6"], ["Décisions", "États de versement"],
    "Contrôler l'enveloppe, les bénéficiaires et le calcul."),

  // ───────── GRETA (budget annexe) ─────────
  c("greta-salaires", "greta", "Salaires / vacations formateurs", "Salaires et vacations des formateurs GRETA",
    "Contrôler les rémunérations et vacations des formateurs (heures, taux, service fait).", "important",
    ["M9-6 budgets annexes", "Décret 86-83", "Convention GRETA"], ["États de paie", "États de vacations", "Service fait"],
    "Rapprocher heures vendues/réalisées et heures payées ; contrôler taux et service fait.",
    { budgets: ["GRETA"], alerteAuto: "Vacations formateurs GRETA sans service fait ou hors barème." }),
  c("greta-conv", "greta", "Conventions", "Conventions de formation et financements",
    "Vérifier les conventions, leur exécution et leur comptabilisation.", "moyen",
    ["M9-6", "Code éduc."], ["Conventions", "Factures", "Bilans pédagogiques"],
    "Rapprocher conventions, produits et charges.", { budgets: ["GRETA"] }),
  c("greta-equilibre", "greta", "Équilibre financier", "Équilibre du budget annexe GRETA",
    "Apprécier l'équilibre charges/produits et le résultat du GRETA.", "important",
    ["M9-6 budgets annexes"], ["Compte de résultat GRETA", "Balance"],
    "Analyser résultat, CAF et couverture des charges.", { budgets: ["GRETA"] }),

  // ───────── CFA (budget annexe) ─────────
  c("cfa-salaires", "cfa", "Salaires / vacations", "Salaires et vacations apprentissage (CFA)",
    "Contrôler les rémunérations et vacations des intervenants du CFA.", "important",
    ["M9-6 budgets annexes", "Décret 86-83"], ["États de paie", "États de vacations", "Service fait"],
    "Rapprocher heures et service fait ; contrôler taux et imputation sur le budget CFA.",
    { budgets: ["CFA"], alerteAuto: "Vacations CFA sans service fait ou taux non conforme." }),
  c("cfa-opco", "cfa", "OPCO / NPEC", "Financement OPCO et niveaux de prise en charge",
    "Vérifier les ressources OPCO et la cohérence des NPEC.", "important",
    ["Code du travail", "Réglementation apprentissage"], ["Conventions OPCO", "NPEC", "Factures"],
    "Rapprocher effectifs apprentis, NPEC et facturation OPCO.", { budgets: ["CFA"] }),
  c("cfa-equilibre", "cfa", "Équilibre budgétaire", "Équilibre du budget annexe CFA",
    "Apprécier l'équilibre du CFA (charges, produits, taxe d'apprentissage C/7568x).", "important",
    ["M9-6 budgets annexes"], ["Compte de résultat CFA", "Balance"],
    "Analyser résultat, ressources OPCO et taxe d'apprentissage.", { budgets: ["CFA"] }),

  // ───────── Compte financier ─────────
  c("cf-annexes", "compte_financier", "Annexes", "Complétude des annexes du compte financier",
    "Vérifier la présence et la cohérence des annexes (P1→P16+, plan CIF).", "important",
    ["M9-6 tome 3", "GBCP"], ["Compte financier", "Annexes"],
    "Contrôler la complétude des pièces et la cohérence des ratios.",
    { alerteAuto: "Annexes du compte financier incomplètes." }),
  c("cf-coherence", "compte_financier", "Cohérence", "Cohérence des données du compte financier",
    "Vérifier la cohérence entre balance, résultat et bilan.", "moyen",
    ["M9-6"], ["Compte financier", "Balance"],
    "Rapprocher les agrégats ; détecter les incohérences."),

  // ───────── Gouvernance (compléments) ─────────
  c("gouv-ca-actes", "gouvernance", "Actes du CA", "Caractère exécutoire des actes du CA",
    "Vérifier la transmission au contrôle de légalité et le caractère exécutoire des actes.", "moyen",
    ["Code éduc. L421-14", "R421-54"], ["Actes du CA", "Accusés de transmission"],
    "Contrôler la transmission des actes budgétaires et leur exécutabilité avant exécution."),
  c("gouv-budget-vote", "gouvernance", "Budget", "Vote et notification du budget dans les délais",
    "S'assurer du vote du budget et des DBM dans les délais réglementaires.", "moyen",
    ["Code éduc. R421-58", "M9-6"], ["Budget voté", "DBM", "Délibérations"],
    "Vérifier les dates de vote, de notification et l'équilibre réel du budget."),
  c("gouv-archivage", "gouvernance", "Traçabilité", "Archivage des PV de CA / commission permanente",
    "Vérifier la conservation et l'accessibilité des PV et délibérations.", "faible",
    ["Code éduc.", "RGP 2022-408"], ["PV de CA", "Registre des délibérations"],
    "Contrôler la tenue du registre et la complétude des PV."),

  // ───────── Comptabilité générale (compléments) ─────────
  c("compta-rattachement", "comptabilite", "Rattachement à l'exercice", "Charges et produits rattachés au bon exercice",
    "Vérifier le rattachement des charges/produits (408/418, 486/487).", "moyen",
    ["M9-6", "GBCP"], ["Balance", "Écritures d'inventaire"],
    "Contrôler les écritures de rattachement et de régularisation de fin d'exercice."),
  c("compta-cca-pca", "comptabilite", "Comptes de régularisation", "Charges/produits constatés d'avance (486/487)",
    "Vérifier la régularité des charges et produits constatés d'avance.", "faible",
    ["M9-6"], ["Balance comptes 486/487", "Justificatifs"],
    "Contrôler la justification et la reprise des comptes de régularisation."),
  c("compta-liaison", "comptabilite", "Comptes de liaison", "Comptes de liaison du groupement (185/186)",
    "Vérifier la réciprocité des comptes de liaison entre budgets/établissements.", "moyen",
    ["M9-6 budgets annexes"], ["Balances", "Comptes 185/186"],
    "Rapprocher les soldes réciproques des comptes de liaison.",
    { alerteAuto: "Comptes de liaison du groupement non réciproques." }),
  c("compta-tva", "comptabilite", "TVA", "Régime et déclarations de TVA (activités assujetties)",
    "Vérifier le traitement de la TVA pour les activités assujetties (GRETA, ventes).", "moyen",
    ["CGI", "M9-6"], ["Déclarations TVA", "Comptes 4456/4457"],
    "Contrôler la collecte, la déduction et les déclarations de TVA."),

  // ───────── Dépenses (compléments) ─────────
  c("dep-engagement", "depenses", "Engagement", "Engagement préalable et disponibilité des crédits",
    "Vérifier l'engagement préalable et le contrôle de disponibilité des crédits.", "important",
    ["GBCP art. 30", "M9-6"], ["Engagements", "Situation des crédits"],
    "Contrôler l'antériorité de l'engagement et la disponibilité des crédits.",
    { alerteAuto: "Dépense engagée sans crédits disponibles." }),
  c("dep-imputation", "depenses", "Imputation", "Imputation comptable et budgétaire correcte",
    "Vérifier l'imputation par compte et par domaine/activité Op@le.", "moyen",
    ["M9-6", "Op@le"], ["Demandes de paiement", "Balance"],
    "Échantillonner et contrôler l'imputation (compte 6 chiffres, activité)."),
  c("dep-subventions", "depenses", "Subventions versées", "Subventions et participations justifiées",
    "Vérifier la base délibérée et la justification des subventions versées.", "moyen",
    ["Code éduc.", "M9-6"], ["Délibérations", "Conventions", "Justificatifs"],
    "Contrôler la délibération préalable et l'emploi conforme."),
  c("dep-deplacements", "depenses", "Frais de déplacement", "Frais de déplacement conformes au barème",
    "Vérifier les ordres de mission et l'application du barème.", "faible",
    ["Décret 2006-781", "M9-6"], ["Ordres de mission", "États de frais"],
    "Rapprocher missions, justificatifs et barème ; détecter les anomalies."),

  // ───────── Recettes (compléments) ─────────
  c("rec-tarifs", "recettes", "Tarification", "Tarifs délibérés par le conseil d'administration",
    "Vérifier que tous les tarifs appliqués ont été délibérés par le CA.", "important",
    ["Code éduc. R421-20", "M9-6"], ["Délibérations tarifs", "Grille tarifaire"],
    "Rapprocher les tarifs facturés et les tarifs délibérés.",
    { alerteAuto: "Tarifs appliqués non délibérés par le conseil d'administration." }),
  c("rec-dp-internat", "recettes", "Demi-pension / internat", "Facturation demi-pension / internat",
    "Vérifier la facturation (forfait/quotient), les remises d'ordre et les effectifs.", "moyen",
    ["Code éduc.", "M9-6", "Règlement du service de restauration"], ["Rôles", "États SIECLE", "Remises d'ordre"],
    "Rapprocher effectifs, jours et facturation ; contrôler les remises d'ordre."),
  c("rec-conventions", "recettes", "Conventions", "Conventions d'hébergement / restauration / location",
    "Vérifier l'existence et l'exécution comptable des conventions de recettes.", "faible",
    ["Code éduc.", "M9-6"], ["Conventions", "Titres émis"],
    "Rapprocher conventions et produits constatés."),
  c("rec-objets", "recettes", "Objets confectionnés / ventes", "Recettes d'objets confectionnés et ventes",
    "Vérifier le suivi des ventes de produits/objets confectionnés (atelier, SRH).", "faible",
    ["M9-6"], ["États de ventes", "Comptes 701/707"],
    "Contrôler la traçabilité des ventes et leur encaissement."),

  // ───────── Recouvrement / contentieux ─────────
  c("recouv-relances", "recouvrement", "Relances", "Relances amiables graduées et tracées",
    "Vérifier l'existence et la traçabilité des relances avant phase contentieuse.", "moyen",
    ["M9-6", "Code éduc."], ["Lettres de relance", "Journal des relances"],
    "Contrôler la gradation (amiable → mise en demeure) et l'horodatage."),
  c("recouv-satd", "recouvrement", "SATD", "Régularité des SATD émises",
    "Vérifier l'autorisation, le tiers détenteur et la notification des SATD.", "important",
    ["CGPPP", "Code des procédures civiles d'exécution", "M9-6"], ["SATD", "Accusés de réception", "Autorisations"],
    "Contrôler la base juridique, le tiers et le respect du formalisme.",
    { alerteAuto: "SATD émise sans autorisation ou notification régulière." }),
  c("recouv-anv", "recouvrement", "Admissions en non-valeur", "ANV justifiées et délibérées",
    "Vérifier les diligences préalables et la délibération des ANV.", "moyen",
    ["M9-6", "Code éduc. R421-20"], ["États ANV", "Délibérations CA", "Justificatifs de diligences"],
    "Contrôler l'épuisement des diligences avant proposition d'ANV."),
  c("recouv-prescription", "recouvrement", "Prescription", "Suivi de la prescription des créances",
    "Vérifier le suivi des délais de prescription et l'interruption par actes.", "critique",
    ["L218-2 Code civil", "CGPPP", "M9-6"], ["Balance âgée", "Actes interruptifs"],
    "Identifier les créances à risque de prescription et les diligences associées.",
    { alerteAuto: "Créances atteintes/proches de la prescription faute de diligences." }),

  // ───────── Trésorerie (compléments) ─────────
  c("treso-placements", "tresorerie", "Placements", "Régularité des placements d'excédents",
    "Vérifier l'autorisation et la régularité d'éventuels placements.", "faible",
    ["M9-6", "Code monétaire et financier"], ["Délibérations", "Relevés"],
    "Contrôler la base juridique et la sécurité des placements."),
  c("treso-dft", "tresorerie", "Compte DFT", "Tenue du compte DFT (pas de découvert)",
    "Vérifier l'absence de position débitrice du compte au Trésor.", "important",
    ["M9-6", "Convention DFT"], ["Relevés DFT", "Journal de trésorerie"],
    "Contrôler les positions et l'interdiction de découvert.",
    { alerteAuto: "Position débitrice (découvert) du compte au Trésor." }),

  // ───────── Régies (compléments) ─────────
  c("reg-reversement", "regies", "Reversements", "Reversement des recettes dans les délais",
    "Vérifier la périodicité de reversement des recettes au comptable.", "moyen",
    ["Décret 2019-798", "M9-6"], ["Journaux de régie", "Bordereaux de versement"],
    "Contrôler les délais de reversement et le respect du plafond.",
    { alerteAuto: "Recettes de régie non reversées dans les délais." }),
  c("reg-fonds-caisse", "regies", "Fonds de caisse", "Fonds de caisse justifié et conforme",
    "Vérifier le montant et la justification du fonds de caisse.", "faible",
    ["Décret 2019-798", "M9-6"], ["Acte de régie", "Comptes de régie"],
    "Rapprocher le fonds de caisse autorisé et constaté."),
  c("reg-cloture", "regies", "Clôture / apurement", "Apurement et clôture des régies",
    "Vérifier l'apurement des opérations et la clôture régulière des régies inactives.", "moyen",
    ["Décret 2019-798", "M9-6"], ["Comptes de régie", "Arrêtés de clôture"],
    "Contrôler l'apurement final et la reddition des comptes du régisseur."),

  // ───────── Valeurs inactives ─────────
  c("vi-registre", "valeurs_inactives", "Registre", "Tenue du registre P503 des valeurs inactives",
    "Vérifier la tenue et la mise à jour du registre des valeurs inactives.", "moyen",
    ["M9-6", "Instruction valeurs inactives"], ["Registre P503", "Bordereaux"],
    "Contrôler les entrées/sorties et le solde des valeurs inactives."),
  c("vi-controle-ac", "valeurs_inactives", "Contrôle AC", "Contrôle de l'agent comptable",
    "Vérifier le contrôle périodique de l'AC sur les valeurs inactives.", "moyen",
    ["M9-6"], ["PV de contrôle", "Registre P503"],
    "Contrôler la périodicité et la traçabilité du contrôle de l'AC.",
    { alerteAuto: "Valeurs inactives sans contrôle de l'agent comptable." }),
  c("vi-recolement", "valeurs_inactives", "Récolement", "PV de récolement des valeurs inactives",
    "Vérifier le récolement physique et sa concordance avec le registre.", "faible",
    ["M9-6"], ["PV de récolement", "Registre P503"],
    "Rapprocher le stock physique et le registre."),

  // ───────── Immobilisations (compléments) ─────────
  c("immo-amort", "immobilisations", "Amortissements", "Plan et durées d'amortissement conformes",
    "Vérifier l'application d'un plan d'amortissement cohérent.", "moyen",
    ["M9-6", "RGP 2022-408"], ["Plan d'amortissement", "Comptes 28x"],
    "Contrôler la cohérence des durées et la dotation aux amortissements."),
  c("immo-mad", "immobilisations", "Biens mis à disposition", "Suivi des biens mis à disposition par la collectivité",
    "Vérifier le suivi des biens remis par la collectivité (compte 22x / hors bilan).", "faible",
    ["M9-6", "Code éduc."], ["Inventaire collectivité", "Comptes 22x"],
    "Rapprocher l'inventaire des biens mis à disposition et la comptabilité."),

  // ───────── Stocks (compléments) ─────────
  c("stock-srh", "stocks", "Denrées SRH", "Gestion des stocks de denrées (SRH)",
    "Vérifier la rotation, la casse et la valorisation des denrées.", "moyen",
    ["M9-6 — comptabilité matières"], ["Inventaire denrées", "Comptes 31/603"],
    "Contrôler les mouvements, la casse et le crédit nourriture associé."),
  c("stock-magasin", "stocks", "Magasin / sorties", "Traçabilité des entrées/sorties de magasin",
    "Vérifier la traçabilité des mouvements de magasin.", "faible",
    ["M9-6"], ["Fiches de stock", "Bons de sortie"],
    "Contrôler la tenue des fiches de stock et les sorties justifiées."),

  // ───────── Commande publique (compléments) ─────────
  c("cp-recensement", "commande_publique", "Recensement", "Recensement des besoins et computation des seuils",
    "Vérifier le recensement annuel et la computation des seuils par famille.", "important",
    ["CCP", "Code de la commande publique"], ["Tableau de recensement", "Familles d'achat"],
    "Contrôler la computation des seuils par nature/famille homogène.",
    { alerteAuto: "Absence de computation des seuils par famille d'achat." }),
  c("cp-execution", "commande_publique", "Exécution", "Exécution des marchés et avenants",
    "Vérifier la régularité de l'exécution, des avenants et des pénalités.", "moyen",
    ["CCP"], ["Marchés", "Avenants", "Décomptes"],
    "Contrôler les avenants (seuil, motif) et l'application des clauses."),
  c("cp-pj-marche", "commande_publique", "Pièces du marché", "Pièces justificatives du marché complètes",
    "Vérifier la complétude du dossier de marché (PJ exigibles au paiement).", "moyen",
    ["CCP", "Décret PJ"], ["Dossier de marché", "Demandes de paiement"],
    "Contrôler la présence des pièces exigibles à chaque paiement."),

  // ───────── Ressources humaines (compléments) ─────────
  c("rh-hs", "rh", "Heures supplémentaires", "HSE / HSA justifiées et plafonnées",
    "Vérifier la justification et les plafonds des heures supplémentaires.", "moyen",
    ["Textes indemnitaires", "M9-6"], ["États HSE/HSA", "Service fait"],
    "Rapprocher heures payées et service fait ; contrôler les plafonds.",
    { alerteAuto: "Heures supplémentaires payées sans service fait justifié." }),
  c("rh-frais-mission", "rh", "Frais de mission RH", "Frais de mission des personnels conformes",
    "Vérifier les ordres de mission et l'application du barème.", "faible",
    ["Décret 2006-781"], ["Ordres de mission", "États de frais"],
    "Contrôler la régularité et le barème des frais de mission."),

  // ───────── Logements de fonction ─────────
  c("log-acte", "logements", "Concession", "Acte de concession (NAS / COP / COG)",
    "Vérifier l'existence d'un acte de concession conforme (nécessité/utilité de service).", "important",
    ["CGPPP R.2124-65", "Décret 2012-752", "Code éduc. R216-4 à R216-19"], ["Arrêté de concession", "Délibération collectivité"],
    "Contrôler la base juridique de la concession et son type (NAS/COP/COG)."),
  c("log-titre", "logements", "Titre exécutoire", "Titre exécutoire / ordre de recettes remis à l'occupant",
    "Vérifier l'émission d'un titre exécutoire pour la redevance d'occupation.", "critique",
    ["CGPPP", "M9-6", "Code éduc."], ["Ordre de recettes", "Titre exécutoire", "Acte de concession"],
    "Rapprocher concessions par utilité de service et titres de redevance émis.",
    { alerteAuto: "Logement (COP/COG) occupé sans titre exécutoire / ordre de recettes." }),
  c("log-conso", "logements", "Consommations", "Relevés de consommations et report d'index N→N+1",
    "Vérifier le relevé des consommations (eau/élec/gaz/chauffage) et le report d'index.", "moyen",
    ["Code éduc.", "M9-6"], ["Relevés d'index", "Registre des consommations"],
    "Contrôler la continuité des index (report N→N+1) et la refacturation."),
  c("log-charges", "logements", "Décompte de charges", "Décompte de charges réelles vs provisions",
    "Vérifier le décompte annuel des charges et la régularisation des provisions.", "moyen",
    ["Code éduc.", "M9-6"], ["Décompte de charges", "Provisions appelées"],
    "Rapprocher charges réelles et provisions ; contrôler la régularisation."),

  // ───────── Fonds sociaux / bourses ─────────
  c("fs-decision", "fonds_sociaux", "Attribution", "Décision d'attribution régulière (commission)",
    "Vérifier la régularité des décisions d'attribution des aides (commission, CE).", "moyen",
    ["Code éduc.", "Circulaires fonds sociaux"], ["PV de commission", "Décisions d'attribution"],
    "Contrôler la base (commission/CE) et la traçabilité des décisions."),
  c("fs-cantine", "fonds_sociaux", "Imputation", "Fonds social cantine : extinction de la créance",
    "Vérifier que l'aide à la restauration éteint la créance (411) et n'est pas versée à la famille.", "critique",
    ["M9-6", "Circulaires fonds sociaux"], ["Décisions d'aide", "Écritures 411"],
    "Contrôler l'imputation : aide demi-pension → extinction créance C/411, pas de versement direct.",
    { alerteAuto: "Fonds social restauration versé à la famille au lieu d'éteindre la créance (411)." }),
  c("fs-rgpd", "fonds_sociaux", "RGPD", "Traçabilité et confidentialité des bénéficiaires",
    "Vérifier la conformité RGPD du traitement des bénéficiaires d'aides.", "moyen",
    ["RGPD art. 30", "Code éduc."], ["Registre des traitements", "Habilitations"],
    "Contrôler la minimisation, l'accès restreint et la traçabilité des données sensibles."),

  // ───────── Compte financier (compléments) ─────────
  c("cf-depot", "compte_financier", "Dépôt", "Dépôt du compte financier dans les délais (Infocentre)",
    "Vérifier la préparation et le dépôt du compte financier (Infocentre) dans les délais.", "important",
    ["M9-6 tome 3", "Code éduc."], ["Compte financier", "Accusé de dépôt"],
    "Contrôler la complétude et le respect du calendrier de dépôt."),
  c("cf-ca-avril", "compte_financier", "Présentation CA", "Présentation au CA avant fin avril",
    "Vérifier la présentation du compte financier au CA avant la fin avril.", "moyen",
    ["Code éduc. R421-77", "M9-6"], ["Convocation CA", "Délibération"],
    "Contrôler la date de présentation et la délibération du CA.",
    { alerteAuto: "Compte financier non présenté au CA avant fin avril." }),
  c("cf-cif", "compte_financier", "Plan CIF", "Plan de comptes CIF obligatoire renseigné",
    "Vérifier le renseignement du plan CIF et la période d'inventaire.", "moyen",
    ["M9-6 tome 3"], ["Compte financier", "Plan CIF"],
    "Contrôler la présence du plan CIF et la cohérence de la période d'inventaire."),
];

/** Contrôles applicables à un type de budget (filtre domaines + contrôles). */
export function controlesPourBudget(budget: "EPLE" | "GRETA" | "CFA"): ControleDef[] {
  return CONTROLES.filter((ct) => {
    const dom = DOMAINES.find((d) => d.id === ct.domaineId);
    if (dom?.budgets && !dom.budgets.includes(budget)) return false;
    if (ct.budgets && !ct.budgets.includes(budget)) return false;
    return true;
  });
}

export const domaineLabel = (id: string) => DOMAINES.find((d) => d.id === id)?.libelle ?? id;
