/**
 * Fallback du référentiel `comptes_sens_normal_ref` — utilisé :
 *   - quand l'app tourne hors-ligne / sans session ;
 *   - dans les scripts de recette Node (sans DB).
 *
 * Liste minimale couvrant les cas critiques exigés par le cahier des charges.
 * En production, le référentiel complet (102 comptes) est chargé depuis
 * Supabase via `loadReferentiel()`.
 */

import type { CompteRef } from './referentielTypes';

export const REFERENTIEL_FALLBACK: CompteRef[] = [
  // CRITIQUES
  { compte: '281100', libelle: 'Amort. terrains', classe: 2, sous_classe: '28', sens_normal: 'C', sens_cloture: 'C', despecialisable: true, type_compte: 'amort', niveau_alerte_si_anormal: 'critique', message_alerte: 'Amortissements TOUJOURS créditeurs', cause_probable: 'Erreur dotation', action_corrective: 'Vérifier 6811', reference_m96: 'M9-6 T1 §2.8', actif: true },
  { compte: '281300', libelle: 'Amort. bâtiments', classe: 2, sous_classe: '28', sens_normal: 'C', sens_cloture: 'C', despecialisable: true, type_compte: 'amort', niveau_alerte_si_anormal: 'critique', message_alerte: 'Amortissements TOUJOURS créditeurs', cause_probable: 'Erreur dotation', action_corrective: 'Vérifier 6811', reference_m96: 'M9-6 T1 §2.8', actif: true },
  { compte: '411200', libelle: 'Familles DP', classe: 4, sous_classe: '41', sens_normal: 'D', sens_cloture: 'D_ou_nul', despecialisable: true, type_compte: 'tiers_client', niveau_alerte_si_anormal: 'critique', message_alerte: 'Créances familles : SOLDE CRÉDITEUR = TROP-PERÇU (RGP 2022-408)', cause_probable: 'Encaissement avant titre', action_corrective: 'Émettre titre de remboursement', reference_m96: 'Ord. 2022-408 art. 11', actif: true },
  { compte: '411300', libelle: 'Familles internat', classe: 4, sous_classe: '41', sens_normal: 'D', sens_cloture: 'D_ou_nul', despecialisable: true, type_compte: 'tiers_client', niveau_alerte_si_anormal: 'critique', message_alerte: 'Créances familles : SOLDE CRÉDITEUR = TROP-PERÇU (RGP 2022-408)', cause_probable: 'Encaissement avant titre', action_corrective: 'Émettre titre de remboursement', reference_m96: 'Ord. 2022-408 art. 11', actif: true },
  { compte: '443110', libelle: 'Bourses crédit à répartir', classe: 4, sous_classe: '44', sens_normal: 'C', sens_cloture: 'C_ou_nul', despecialisable: false, type_compte: 'etat', niveau_alerte_si_anormal: 'critique', message_alerte: 'Compte 443110 NON-DÉSPÉCIALISABLE — solde DÉBITEUR = bourses payées sans réception préalable', cause_probable: 'Paiement bourses sans avance État', action_corrective: 'Solliciter avance académique', reference_m96: 'M9-6 T2 §4.431', actif: true },
  { compte: '467000', libelle: 'Comptes débiteurs/créditeurs', classe: 4, sous_classe: '46', sens_normal: 'C_ou_nul', sens_cloture: 'nul', despecialisable: true, type_compte: 'attente', niveau_alerte_si_anormal: 'critique', message_alerte: 'Compte 467 NON NUL en CLÔTURE = critique', cause_probable: 'Imputation manquante', action_corrective: 'Apurer avant 31/12', reference_m96: 'M9-6 T3 §4.67', actif: true },
  { compte: '471000', libelle: 'Recettes à classer', classe: 4, sous_classe: '47', sens_normal: 'variable', sens_cloture: 'nul', despecialisable: true, type_compte: 'attente', niveau_alerte_si_anormal: 'critique', message_alerte: 'Compte 471 NON NUL en CLÔTURE = critique', cause_probable: 'Encaissement non imputé', action_corrective: 'Apurer avant 31/12', reference_m96: 'M9-6 T3 §4.71', actif: true },
  { compte: '472000', libelle: 'Dépenses à classer', classe: 4, sous_classe: '47', sens_normal: 'variable', sens_cloture: 'nul', despecialisable: true, type_compte: 'attente', niveau_alerte_si_anormal: 'critique', message_alerte: 'Compte 472 NON NUL en CLÔTURE = critique', cause_probable: 'Décaissement non imputé', action_corrective: 'Apurer avant 31/12', reference_m96: 'M9-6 T3 §4.72', actif: true },
  { compte: '473000', libelle: 'Recettes à régulariser', classe: 4, sous_classe: '47', sens_normal: 'variable', sens_cloture: 'nul', despecialisable: true, type_compte: 'attente', niveau_alerte_si_anormal: 'critique', message_alerte: 'Compte 473 NON NUL en CLÔTURE = critique', cause_probable: 'Régularisation pendante', action_corrective: 'Apurer avant 31/12', reference_m96: 'M9-6 T3 §4.73', actif: true },
  { compte: '474000', libelle: 'Dépenses à régulariser', classe: 4, sous_classe: '47', sens_normal: 'variable', sens_cloture: 'nul', despecialisable: true, type_compte: 'attente', niveau_alerte_si_anormal: 'critique', message_alerte: 'Compte 474 NON NUL en CLÔTURE = critique', cause_probable: 'Régularisation pendante', action_corrective: 'Apurer avant 31/12', reference_m96: 'M9-6 T3 §4.74', actif: true },
  { compte: '475000', libelle: 'Comptes transitoires', classe: 4, sous_classe: '47', sens_normal: 'variable', sens_cloture: 'nul', despecialisable: true, type_compte: 'attente', niveau_alerte_si_anormal: 'critique', message_alerte: 'Compte 475 NON NUL en CLÔTURE = critique', cause_probable: 'Transitoire non soldé', action_corrective: 'Apurer avant 31/12', reference_m96: 'M9-6 T3 §4.75', actif: true },
  { compte: '477000', libelle: 'Comptes d\'attente divers', classe: 4, sous_classe: '47', sens_normal: 'variable', sens_cloture: 'nul', despecialisable: true, type_compte: 'attente', niveau_alerte_si_anormal: 'critique', message_alerte: 'Compte 477 NON NUL en CLÔTURE = critique', cause_probable: 'Imputation manquante', action_corrective: 'Apurer avant 31/12', reference_m96: 'M9-6 T3 §4.77', actif: true },
  { compte: '511200', libelle: 'Chèques à encaisser', classe: 5, sous_classe: '51', sens_normal: 'D', sens_cloture: 'D_ou_nul', despecialisable: true, type_compte: 'financier', niveau_alerte_si_anormal: 'critique', message_alerte: 'Chèques à encaisser ne peuvent JAMAIS être créditeurs', cause_probable: 'Erreur écriture', action_corrective: 'Inverser OD', reference_m96: 'M9-6 T2 §5.11', actif: true },
  { compte: '515100', libelle: 'Trésor compte courant', classe: 5, sous_classe: '51', sens_normal: 'D', sens_cloture: 'D_ou_nul', despecialisable: true, type_compte: 'financier', niveau_alerte_si_anormal: 'critique', message_alerte: 'Compte 515100 ne peut JAMAIS être créditeur (trésorerie négative impossible)', cause_probable: 'Erreur ou découvert', action_corrective: 'Vérifier extrait DFT', reference_m96: 'M9-6 T2 §5.151', actif: true },
  { compte: '515900', libelle: 'Trésor placement', classe: 5, sous_classe: '51', sens_normal: 'C', sens_cloture: 'C_ou_nul', despecialisable: true, type_compte: 'financier', niveau_alerte_si_anormal: 'critique', message_alerte: 'Compte 515900 ne peut JAMAIS être débiteur (placement = passif)', cause_probable: 'Inversion D/C', action_corrective: 'Inverser OD', reference_m96: 'M9-6 T2 §5.159', actif: true },
  { compte: '531000', libelle: 'Caisse principale', classe: 5, sous_classe: '53', sens_normal: 'D', sens_cloture: 'D_ou_nul', despecialisable: true, type_compte: 'financier', niveau_alerte_si_anormal: 'critique', message_alerte: 'Caisse 531 ne peut JAMAIS être créditrice (caisse négative impossible)', cause_probable: 'Décaissement sans encaissement', action_corrective: 'Vérifier billetage', reference_m96: 'M9-6 T2 §5.31', actif: true },
  // Liaison BP/BA
  { compte: '185000', libelle: 'Liaison BP/BA', classe: 1, sous_classe: '18', sens_normal: 'variable', sens_cloture: 'variable', despecialisable: false, type_compte: 'liaison', niveau_alerte_si_anormal: 'majeure', message_alerte: 'Compte 185000 doit refléter le miroir budget annexe', cause_probable: 'Discordance BP/BA', action_corrective: 'Réconcilier les sphères', reference_m96: 'M9-6 T1 §1.85', actif: true },
];

/** Index par compte pour lookup O(1). */
export const REFERENTIEL_FALLBACK_INDEX: Record<string, CompteRef> = Object.fromEntries(
  REFERENTIEL_FALLBACK.map((r) => [r.compte, r]),
);