// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Repli inoffensif quand les variables d'environnement sont absentes (tests / CI) :
// évite que createClient lève « supabaseUrl is required » au chargement du module.
// En production, VITE_SUPABASE_URL est injectée au build → valeurs réelles utilisées.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://placeholder.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "placeholder-anon-key";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Postes partagés EPLE : session en sessionStorage → déconnexion à la
    // fermeture de l'onglet (réduit le risque de session laissée ouverte).
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});